/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://c74xxpbzpvarrbwfghgztzs2o4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-hswsgya3dbffpmesgxnanbtnmi",
    "aws_cognito_identity_pool_id": "us-east-1:17ce6597-df32-4c93-a365-7d300956ff89",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hTh4O1yuq",
    "aws_user_pools_web_client_id": "5qgt610fnl2o3h2mavh3s5o2mu",
    "oauth": {}
};


export default awsmobile;
